export const NATIVE_STRINGS = {
  "action_check_all": "Select all",
  "action_content_add": "Add",
  "action_next": "Next Page",
  "action_ok": "OK",
  "action_order": "Reorder",
  "action_page_settings": "Settings of each Draft",
  "action_previous": "Previous Page",
  "action_refresh": "Refresh",
  "action_save": "Save",
  "action_settings": "Settings",
  "action_tool_bar": "Show toolbar",
  "button_new_item": "New",
  "dialog_button_add": "Add",
  "dialog_button_cancel": "Cancel",
  "dialog_button_close": "Close",
  "dialog_button_delete": "Delete",
  "dialog_button_edit": "Refresh",
  "dialog_button_eraser_reset": "Clear all",
  "dialog_button_fix": "Confirm",
  "dialog_button_no_save": "Leave without saving",
  "dialog_button_save": "Save",
  "dialog_button_share": "Share",
  "dialog_message_confirm_delete": "Do you really wish to delete it?",
  "dialog_message_confirm_eraser_reset": "Do you really wish to delete them all?",
  "dialog_message_confirm_save": "Do you wish to leave the page without saving?",
  "dialog_message_page_limit_error": "Unable to add more page since maximum page limit is reached.",
  "dialog_message_page_list_alert_confirm": "In the latest version, we added page-progression-direction function. You can tick in the box located in the top part of the screen to change apply the function.",
  "dialog_message_paint_alert_confirm": "If you start an application while editing, you might happen to lose all the changes you’ve made. We recommend that you save your works frequently.",
  "dialog_message_release_info_1.2": "Now you can start drawing outside of the canvas! Also, shortcuts can now be added to the volume buttons(please have a look at the settings)! We plan to update even more!! Please write a review too!",
  "dialog_rendition_spread": "Set the first page to double-page spread",
  "dialog_stamp_emotion": "Face",
  "dialog_stamp_human": "Manga Mark",
  "dialog_text_delete_local_name": "Once the transmission is finished, delete the draft saved inside the device.",
  "dialog_text_direction": "Text Direction",
  "dialog_text_dont_show_again": "Do not show this message again",
  "dialog_text_edit_create_name": "Please enter some information for the draft",
  "dialog_text_edit_title": "Edit title",
  "dialog_text_guide": "Guide settings",
  "dialog_text_loading_text_image": "Image being imported",
  "dialog_text_no_title": "No Title",
  "dialog_text_page_direction": "Page-Progression-Direction",
  "dialog_text_size": "Text Size",
  "dialog_text_title": "Title",
  "dialog_text_vertical": "Vertical",
  "dialog_title_add_stamp": "Add stamp",
  "dialog_title_export": "Select image",
  "dialog_title_page_list_alert_confirm": "Information",
  "dialog_title_paint_alert_confirm": "Note",
  "dialog_title_release_info": "New Release",
  "dialog_title_text_insert": "Insert Text",
  "message_action_failed": "Failed",
  "message_connectivity_error": "Network error",
  "message_delete_no_authority_error": "Since you are not the team owner, deletion cannot be done",
  "message_empty_text": "No text entered.",
  "message_encode_error": "Contains invalid characters.",
  "message_export_finished": "Exporting finished.",
  "message_externalstorage_not_found_cannot_use": "Unable to use. External storage not found.",
  "message_loading": "Now saving",
  "message_need_permission": "Permission is required to share / save",
  "message_network_error": "Network Error",
  "message_no_export_items": "No valid images.",
  "message_no_items": "No item",
  "message_no_selected_items": "Select an image.",
  "message_no_voice_input_app": "Voice recognition not supported",
  "message_page_copied": "Page copied.",
  "message_save_fail": "Saving failed",
  "message_save_fail_empty_page": "Blank pages cannot be saved.",
  "message_save_success": "Saved",
  "message_share_fail_empty_page": "Blank pages cannot be shared.",
  "message_text_image_size_error": "Number of characters per line is too many.",
  "message_update_to_required_version": "Please update to the latest version.",
  "message_warning_cannot_save_in_device": "\"If you're having problems saving it could be due to insufficient hard drive space.\"",
  "name_popup_delete": "Delete",
  "name_popup_edit_title": "Edit Title",
  "page_popup_copy": "Copy",
  "pref_category_title_settings": "Settings",
  "pref_dominant_hand_default_value": "right_handed",
  "pref_dominant_hand_dialog_title": "@string/pref_dominant_hand_title",
  "pref_dominant_hand_summary": "Change the location of full screen button",
  "pref_dominant_hand_title": "Dominant Hand Settings",
  "pref_volume_control_default_value": "none",
  "pref_volume_control_dialog_title": "@string/pref_volume_control_title",
  "pref_volume_control_summary": "Select the process when pressing the volume button on the paint screen",
  "pref_volume_control_title": "Volume Control Button Settings",
  "sample_name_title": "Sample Draft",
  "tab_title_local": "Device",
  "text_account_creation": "Sign up using Email",
  "text_app_version": "The version of your application",
  "text_mail_address": "E-mail",
  "text_page": "Page",
  "text_password": "Password",
  "text_password_confirmation": "Forgot password?"
} as const;
export const STAMPS = [
  "stamp_face_f_001",
  "stamp_face_f_002",
  "stamp_face_f_003",
  "stamp_face_f_004",
  "stamp_face_f_005",
  "stamp_face_f_006",
  "stamp_face_f_007",
  "stamp_face_f_008",
  "stamp_face_f_009",
  "stamp_face_f_010",
  "stamp_face_f_011",
  "stamp_face_f_012",
  "stamp_face_f_013",
  "stamp_face_f_014",
  "stamp_face_f_015",
  "stamp_face_f_016",
  "stamp_face_f_017",
  "stamp_face_f_018",
  "stamp_face_f_019",
  "stamp_face_f_020",
  "stamp_face_f_021",
  "stamp_face_f_022",
  "stamp_face_f_023",
  "stamp_face_f_024",
  "stamp_face_f_025",
  "stamp_face_f_026",
  "stamp_face_f_027",
  "stamp_face_f_028",
  "stamp_face_f_029",
  "stamp_face_f_030",
  "stamp_face_m_001",
  "stamp_face_m_002",
  "stamp_face_m_003",
  "stamp_face_m_004",
  "stamp_face_m_005",
  "stamp_face_m_006",
  "stamp_face_m_007",
  "stamp_face_m_008",
  "stamp_face_m_009",
  "stamp_face_m_010",
  "stamp_face_m_011",
  "stamp_face_m_012",
  "stamp_face_m_013",
  "stamp_face_m_014",
  "stamp_face_m_015",
  "stamp_face_m_016",
  "stamp_face_m_017",
  "stamp_face_m_018",
  "stamp_face_m_019",
  "stamp_face_m_020",
  "stamp_face_m_021",
  "stamp_face_m_022",
  "stamp_face_m_023",
  "stamp_face_m_024",
  "stamp_face_m_025",
  "stamp_face_m_026",
  "stamp_face_m_027",
  "stamp_face_m_028",
  "stamp_face_m_029",
  "stamp_face_m_030",
  "stamp_icon_001",
  "stamp_icon_002",
  "stamp_icon_003",
  "stamp_icon_004",
  "stamp_icon_005",
  "stamp_icon_006",
  "stamp_icon_007",
  "stamp_icon_008",
  "stamp_icon_009",
  "stamp_icon_010",
  "stamp_icon_011",
  "stamp_icon_012",
  "stamp_icon_013",
  "stamp_icon_014",
  "stamp_icon_015",
  "stamp_icon_016",
  "stamp_icon_017",
  "stamp_icon_018",
  "stamp_icon_019",
  "stamp_icon_020",
  "stamp_icon_fukidasi",
  "stamp_icon_fukidasi2"
];
